version: "3"
services:
  
  mongodb:
    
    image: mongo
    
    ports:
     - 27017:27017
    
    environment:
       MONGO_INITDB_ROOT_USERNAME: breiline
       MONGO_INITDB_ROOT_PASSWORD: "1234"
    command: mongod --bind_ip_all



  mongo-express:

    image: mongo-express

    ports:
     - 8081:8081
    environment:
      ME_CONFIG_MONGODB_SERVER: mongodb
      ME_CONFIG_MONGODB_ADMINUSERNAME: breiline
      ME_CONFIG_MONGODB_ADMINPASSWORD: "1234"